name: IOT IJK ANDROID DEBUG CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download r25c NDK
        run: |
          curl -L -o android-ndk-r25c-darwin.dmg https://dl.google.com/android/repository/android-ndk-r25c-darwin.dmg
          hdiutil attach -nobrowse -mountpoint /Volumes/ndk android-ndk-r25c-darwin.dmg
          mkdir -p "$GITHUB_WORKSPACE/android-ndk-r25c"
          cp -R /Volumes/ndk/AndroidNDK*.app/Contents/NDK/. "$GITHUB_WORKSPACE/android-ndk-r25c/"
          hdiutil detach /Volumes/ndk
          ls -l "$GITHUB_WORKSPACE/android-ndk-r25c"
      - name: Update SDK Version
        run: bash .github/script/updateVersionForSnapshot.sh
      - uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: '17'

      - name: Build with Gradle
        run: |
          set -e
          export ANDROID_NDK="$GITHUB_WORKSPACE/android-ndk-r25c"
          export ANDROID_NDK_ROOT="$ANDROID_NDK"
          ls -l "$ANDROID_NDK"

          sh .github/script/build_armv7a.sh

          echo "Current directory before cd: $(pwd)"
          cd android/ijkplayer

          echo "Checking armv7a .so files..."
          ls -l ijkplayer-armv7a/src/main/libs/armeabi-v7a/*.so
          echo "Checking arm64 .so files..."
          ls -l ijkplayer-arm64/src/main/libs/arm64-v8a/*.so

          ./gradlew :ijkplayer-armv7a:assemble
          ./gradlew :ijkplayer-arm64:assemble
          ./gradlew :ijkplayer-java:assemble

      - name: Upload AARs and so
        uses: actions/upload-artifact@v4
        with:
          name: aars
          path: |
            android/ijkplayer/ijkplayer-armv7a/src/main/obj/local
            android/ijkplayer/ijkplayer-arm64/src/main/obj/local
            android/ijkplayer/ijkplayer-armv7a/build/outputs/aar/ijkplayer-armv7a-debug.aar
            android/ijkplayer/ijkplayer-arm64/build/outputs/aar/ijkplayer-arm64-debug.aar
            android/ijkplayer/ijkplayer-java/build/outputs/aar/ijkplayer-java-debug.aar